word_dict = {
    # Section 1
    "Abash": "to make ashamed; to embarrass",
    "Abate": "to subside; to reduce",
    "Abdicate": "to step down from a position of power or responsibility",
    "Aberration": "something not typical; a deviation from the standard",
    "Abhor": "to hate very, very much; to detest",
    "Abject": "hopeless; extremely sad and servile; defeated",
    "Abnegate": "to deny oneself things; to reject; to renounce",
    "Abortive": "unsuccessful",
    "Abridge": "to shorten; to condense",
    "Absolute": "total; unlimited",
    "Absolve": "to forgive or free from blame; to free from sin; to free from an obligation",
    # Section 2
    "Abstinent": "abstaining; voluntarily not doing something, especially something pleasant that is bad for you or has a bad reputation",
    "Abstract": "theoretical; impersonal",
    "Abstruse": "hard to understand",
    "Abysmal": "extremely hopeless or wretched; bottomless",
    "Accolade": "an award; an honor",
    "Accost": "to approach and speak to someone aggressively",
    "Acerbic": "sour; severe; like acid in temper, mood, or tone",
    "Acquiesce": "to comply passively; to accept; to assent; to agree",
    "Acrid": "harshly pungent; bitter",
    "Acrimonious": "full of spite; bitter; nasty",
    "Acumen": "keenness of judgment; mental sharpness",
    # Section 3
    "Acute": "sharp; shrewd",
    "Adamant": "stubborn; unyielding; completely inflexible",
    "Address": "to speak to; to direct one's attention to",
    "Adherent": "follower; supporter; believer",
    "Admonish": "to scold gently; to warn",
    "Adriot": "skillful; dexterous; clever; shrewd; socially at ease",
    "Adulation": "wild or excessive admiration; flattery",
    # Section 4
    "Adulterate": "to contaminate; to make impure",
    "Adverse": "unfavorable; antagonistic",
    "Aesthetic": "having to do with artistic beauty; artistic",
    "Affable": "easy to talk to; friendly",
    "Affectation": "unnatural or artificial behavior; usually intended to impress",
    "Affinity": "sympathy; attraction; kinship; similarity",
    "Affluent": "rich; prosperous",
    "Agenda": "program; the things to be done",
    # Section 5
    "Aggregate": "sum total; a collection of separate things mixed together",
    "Agnostic": "one who believes that the existence of a god can be neither proven nor disproven",
    "Agrarian": "relating to land; relating to the management or farming of land",
    "Alacrity": "cheerful eagerness or readiness to respond",
    "Allege": "to assert without proof",
    "Alleviate": "to relieve, usually temporarily or incompletely; to make bearable; to lessen",
    "Allocate": "to distribute; to assign; to allot",
    "Alloy": "a combination of two or more things, usually metals",
    # Section 6
    "Allusion": "an indirect reference (often to a literary work); a hint",
    "Aloof": "uninvolved; standing off; keeping one's distance",
    "Altruism": "selflessness; generosity; devotion to the interest of others",
    "Ambience": "atmosphere; mood; feeling",
    "Ambiguous": "unclear in meaning; confusing; capable of being interpreted in different ways",
    "Ambivalent": "undecided; having opposed feelings simultaneously",
    # Section 7
    "Amenity": "pleasantness; attractive or comfortable feature",
    "Amiable": "friendly; agreeable",
    "Amnesty": "an offical pardon for a group of people who have violated a law or policy",
    "Amoral": "lacking a sense of right and wrong; neither good nor bad, neither moral nor immoral; without moral feelings",
    "Amorous": "feeling loving, especially in a sexual sense; in love; relating to love",
    "Amorphous": "shapeless; without a regular or stable shape; bloblike",
    "Anachronism": "something out of place in time or history; an incongruity",
    "Analogy": "a comparison of one thing to another; similarity",
    # Section 8
    "Anarchy": "absence of government or control; lawlessness; disorder",
    "Anecdote": "a short account of a humorous or revealing incident",
    "Anguish": "agonizing physical or mental pain",
    "Animosity": "resentment; hostility; ill will",
    "Anomaly": "an aberration; an irregularity; a deviation",
    "Antecedent": "someone or something that went before; something that provides a model for something that came after it",
    "Antipathy": "firm dislike; a dislike",
    "Antithesis": "the direct opposite",
    "Apartheid": "the former policy of racial segregation and oppression in the Republic of South Africa",
    # Section 9
    "Apathy": "lack of interest; lack of feeling",
    "Aphorism": "a brief, often witty saying; a proverb",
    "Apocalypse": "a prophetic revelation, especially one concerning the end of the world",
    "Apocryphal": "of dubious authenticity; fictitious; spurious",
    "Apotheosis": "elevation to divine status; the perfect example of something",
    "Appease": "to soothe; to pacify by giving in to",
    "Appreciate": "to increase in value",
    "Apprehensive": "worried; anxious",
    # Section 10
    "Approbation": "approval; praise",
    "Appropriate": "to take without permission; to set aside for a particular use",
    "Aptitude": "capacity for learning; natural ability",
    "Arbiter": "one who decides; a judge",
    "Arbitrary": "random; capricious",
    "Arcane": "mysterious; known only to a select few",
    "Archaic": "extremely old; ancient; outdated",
    # Section 11
    "Archetype": "an original model or pattern",
    "Ardent": "passionate; enthusiastic",
    "Arduous": "hard; difficult",
    "Aristocratic": "of noble birth; snobbish",
    "Artful": "crafty; wily; sly",
    "Artifice": "a clever trick; cunning",
    "Ascendancy": "supremacy; domination",
    "Ascetic": "hermitlike; practicing self-denial",
    "Assiduous": "hardworking; busy; quite diligent",
    # Section 12
    "Assimilate": "to take in, to absorb; to learn thoroughly",
    "Assuage": "to soothe; to pacify; to ease the pain of; to relieve",
    "Astute": "shrewd; keen in judgement",
    "Atheist": "one who does not believe in the existence of any god or divine being",
    "Attrition": "gradual wearing away, weakening, or loss; a natural or expected decrease in numbers or size",
    "Audacity": "boldness; reckless daring; impertinence",
    "Augment": "to make bigger; to add to; to increase",
    "Auspicious": "favorable; promising; pointing to a good result",
    "Austere": "unadorned; stern; forbidding; without excess",
    "Autocratic": "ruling with absolute authority; extremely bossy",
    # Section 13
    "Autonomous": "acting independently",
    "Avarice": "greed; excessive love of riches",
    "Avow": "to claim; to declare boldly; to admit",
    "Avuncular": "like an uncle, especially a nice uncle",
    "Awry": "off course; twisted to one side",
    "Axiom": "a self-evident rule or truth; a widely accepted saying",
    # Section 14
    "Banal": "unoriginal; ordinary",
    "Bane": "poison; torment; cause of harm",
    "Bastion": "stronghold; fortress; fortified place",
    "Beget": "to give birth to; to create; to lead to; to cause",
    "Belabor": "to go over repeatedly or to an absurd extent",
    "Beleaguer": "to surround; to besiege; to harass",
    "Belie": "to give a false impression of; to contradict",
    "Belittle": "to make to seem little; to put someone down",
    # Section 15
    "Belligerent": "combative; quarrelsome; waging war",
    "Bemused": "confused; bewildered",
    "Benefactor": "one who provides help, especially in the form of a gift or donation",
    "Benevolent": "generous; kind; doing good deeds",
    "Benign": "gentle; not harmful; kind; mild",
    # Section 16
    "Bequest": "something left to someone in a will",
    "Bereaved": "deprived or left desolate, especially through death",
    "Beset": "to harass; to surround",
    "Blasphemy": "irreverence; an insult to something held sacred; profanity",
    "Blatant": "unpleasantly or offensively noisy; glaring",
    # Section 17
    "Blight": "a disease in plants; anything that injures or destroys",
    "Blithe": "carefree; cheerful",
    "Bourgeois": "middle class, usually in a pejorative sense; boringly conventional",
    "Bovine": "cow related; cowlike",
    "Brevity": "briefness",
    "Broach": "to open up a subject for discussion, often a delicate subject",
    "Bucolic": "charmingly rural; rustic; countrylike",
    "Bureaucracy": "a system of government administration consisting of numerous"
    " bureaus or offices, especially one run according to inflexible and inefficient"
    " rules; any large administrative system characterized by inefficiency,"
    " lots of rules, and red tape",
    "Burgeon": "to expand; to flourish",
    "Burlesque": "a ludicrous, mocking, lewd imitation",
    # Section 18
    "Cacophony": "harsh-sounding mixture of words, voices, or sounds",
    "Cadence": "rhythm; the rise and fall of sounds",
    "Cajole": "to persuade someone to do something he or she doesn't want to do",
    "Callow": "immature",
    "Candor": "truthfulness; sincere honesty",
    "Capitalism": "an economic system in which businesses are owned by private"
    " citizens (not by the government) and in which the resulting products and"
    " services are sold with relatively little government control",
    "Capitulate": "to surrender; to give up or give in",
    "Capricious": "unpredicatable; likely to change at any moment",
    "Caricature": "a portrait or description that is purposely distorted or exaggerated,"
    " often to prove some point about its subject",
    "Castigate": "to criticize severely; to chastise",
    "Catalyst": "in chemistry, something that changes the rate of chemical reaction"
    " without itself being changed; anyone or anything that makes something happen"
    " without being directly involved in it",
    # Section 19
    "Categorical": "unconditional; absolute",
    "Catharsis": "purification that brings emotional relief or renewal",
    "Catholic": "universal; embracing everything",
    "Caustic": "like acid; corrosive",
    "Celibacy": "abstinence from sex",
    "Censure": "to condemn severely for doing something bad",
    "Cerebral": "brainy; intellectually refined",
    "Chagrin": "humiliation; embarrassed disappointment",
    "Charisma": "a magical-seeming ability to attract followers or inspire loyalty",
    # Section 20
    "Charlatan": "fraud; quack; con man",
    "Chasm": "a deep; gaping hole; a gorge",
    "Chastise": "to inflict punishment on; to discipline",
    "Chicanery": "trickery; deceitfulness; artifice, especially legal or political",
    "Chimera": "an illusion; a foolish fancy",
    "Choleric": "hot-tempered; quick to anger",
    "Chronic": "constant; lasting a long time; inveterate",
    "Chronicle": "a record of events in order of time; a history",
    # Section 21
    "Circuitous": "roundabout; not following a direct path",
    "Circumlocution": "an indirect expression; use of wordy or evasive language",
    "Circumscribe": "to draw a line around; to set the limits; to define; to restrict",
    "Circumspect": "cautious",
    "Circumvent": "to frustrate as though by surrounding",
    "Civil": "polite; civilized; courteous",
    "Clemency": "mercy; forgiveness; mildness",
    "Cliché": "an overused saying or idea",
    "Clique": "an exclusive group bound together by some shared quality or interest",
    # Section 22
    "Coalesce": "to come together as one; to fuse; to unite",
    "Coerce": "to force someone to do or not to do something",
    "Cogent": "powerfully convincing",
    "Cognitive": "dealing with how we know the world around us through our senses; mental",
    "Cognizant": "aware; conscious",
    "Coherent": "holding together; making sense",
    "Colloquial": "conversational; informal in language",
    "Collusion": "conspiracy; secret cooperation",
    "Commensurate": "equal; proportionate",
    "Compelling": "forceful; causing to yield",
    "Compendium": "a summary; an abridgment",
    # Section 23
    "Complacent": "self-satisfied; overly pleased with oneself; contented to a fault",
    "Complement": "to complete or fill up; to be the perfect counterpart",
    "Complicity": "participation in wrongdoing; the act of being an accomplice",
    "Comprehensive": "covering or including everything",
    "Comprise": "to consist of",
    "Conciliatory": "making peace; attempting to resolve a dispute through goodwill",
    "Concise": "brief and to the point; succinct",
    # Section 24
    "Concord": "harmony; agreement",
    "Concurrent": "happening at the same time; parallel",
    "Condescend": "to stoop to someone else's level, usually in an offensive way; to patronize",
    "Condone": "to overlook; to permit to happen",
    "Conducive": "promoting",
    "Confluence": "a flowing together, especially of rivers; the place where they begin to flow together",
    "Congenial": "agreeably suitable; pleasant",
    "Congenital": "describing a trait or condition acquired between conception and birth; innate",
    # Section 25
    "Congregate": "to come together",
    "Conjecture": "to guess; to deduce or infer on slight evidence",
    "Conjure": "to summon or bring into being as if by magic",
    "Connoisseur": "an expert, particularly in matters of art or taste",
    "Consecrate": "to make or declare sacred",
    "Consensus": "unanimity or general agreement",
    "Consonant": "harmonious; in agreement",
    # Section 26
    "Construe": "to interpret",
    "Consummate": "perfect; complete; supremely skillful",
    "Contentious": "argumentative; quarrelsome",
    "Contiguous": "side by side; adjoining",
    "Contingent": "dependent; possible",
    "Contrite": "admitting guilt; especially feeling remorseful",
    "Contrived": "artificial; labored",
    "Conventional": "common; customary; unexceptional",
    "Convivial": "fond of partying; festive",
    "Copious": "abundant; plentiful",
    # Section 27
    "Corollary": "something that follows; a natural consequence",
    "Corroborate": "to confirm; to back up with evidence",
    "Cosmopolitan": "at home in many places or situations; internationally sophisticated",
    "Countenance": "face; facial expression, especially an encouraging one",
    "Coup": "a brilliant victory or accomplishment; the violent overthrow of a government by a small internal group",
    "Covenant": "a solemn agreement; a contract; a pledge",
    "Covert": "secret; hidden",
    "Covet": "to wish for enviously",
    # Section 28
    "Credulous": "eager to believe; gullible",
    "Criterion": "standard; basis for judgement",
    "Cryptic": "mysterious; mystifying",
    "Culinary": "relating to cooking or the kitchen",
    "Culminate": "to climax; to reach full effect",
    # Section 29
    "Culpable": "deserving blame; guilty",
    "Cursory": "hasty; superficial",
    "Curtail": "to shorten; to cut short",
    "Cynic": "one who deeply distrusts human nature; one who believes humans are motivated only by selfishness",
    # Section 30
    "Daunt": "to make fearful; to intimidate",
    "Dearth": "lack; scarcity",
    "Debacle": "violent breakdown; sudden overthrow; overwhelming defeat",
    "Debauchery": "wild living; excessive intemperance",
    "Debilitate": "to weaken; to cripple",
    "Decadent": "decaying or decayed, especially in terms of morals",
    "Decimate": "to kill or destroy a large part of",
    "Decorous": "proper; in good taste; orderly",
    "Deduce": "to conclude from the evidence; to infer",
    "Defame": "to libel or slander; to ruin the good name of",
    # Section 31
    "Deference": "submission to another's will; respect; courtesy",
    "Definitive": "conclusive; providing the last word",
    "Degenerate": "to break down; to deteriorate",
    "Deleterious": "harmful",
    "Delineate": "to describe accurately; to draw in outline",
    "Delude": "to deceive",
    "Deluge": "a flood; an inundation",
    "Demagogue": "a leader who uses prejudice to get more power",
    "Denizen": "inhabitant",
    "Depravity": "extreme wickedness or corruption",
    "Deprecate": "to express disapproval of",
    "Deride": "to ridicule; to laugh at contemptuously",
    # Section 32
    "Derogatory": "disapproving; degrading",
    "Desiccate": "to dry out",
    "Despondent": "extremely depressed; full of despair",
    "Despot": "an absolute ruler; an autocrat",
    "Destitute": "extremely poor; utterly lacking",
    "Desultory": "without a plan or purpose; disconnected; random",
    "Dextrous": "skillful; adriot",
    "Dialectical": "relating to discussions; relating to the rules and methods of reasoning;"
    " approaching truth in the middle of opposing extremes",
    "Dictum": "an authoritative saying; an adage; a maxim; a proverb",
    "Didactic": "intended to teach; morally instructive; pedantic",
    "Diffident": "timid; lacking in self-confidence",
    "Digress": "to stray from the main subject",
    "Dilettante": "someone with superficial knowledge of the arts; an amateur; a dabbler",
    # Section 33
    "Discern": "to have insight; to see things clearly; to discriminate; to differentiate",
    "Discreet": "prudent; judiciously reserved",
    "Discrete": "unconnected; separate; distinct",
    "Discriminate": "to notice or point out the difference between two or more things; to discern; to differentiate",
    "Disdain": "arrogant scorn; contempt",
    "Disinterested": "not taking sides; unbiased",
    "Disparage": "to belittle; to say uncomplimentary things about, usually in a somewhat indirect way",
    # Section 34
    "Disparate": "different; incompatible; unequal",
    "Disseminate": "to spread the seeds of something; to scatter; to make widely known",
    "Dissipate": "to thin out, drift away, or dissolve; to cause to thin out, drift away, or dissolve; to waste or squander",
    "Dissolution": "the breaking up or dissolving of something into parts; disintegration",
    "Distend": "to swell; to extend a great deal",
    "Distinguish": "to tell apart; to cause to stand out",
    "Docile": "easily taught; obedient; easy to handle",
    "Doctrinaire": "inflexibly committed to a doctrine or theory without regard to its practicality; dogmatic",
    "Dogmatic": "arrogantly assertive of uproven ideas; stubbornly claiming that something (often a system of beliefs) is beyond dispute",
    "Domestic": "having to do with the household or family; not foreign",
    # Section 35
    "Dormant": "inactive; as though asleep; asleep",
    "Dubious": "full of doubt; uncertain",
    "Duplicity": "the act of being two-faced; double-dealing; deception",
    # Section 36
    "Ebullient": "boiling; bubbling with excitement; exuberant",
    "Eccentric": "not conventional; a little kooky; irregular",
    "Eclectic": "choosing the best from many sources; drawn from many sources",
    "Edify": "to enlighten; to instruct, especially in moral or religious matters",
    "Efface": "to erase; to rub away the features of",
    "Effusion": "a pouring forth",
    "Egalitarian": "believing in the social and economic equality of all people",
    "Egocentric": "selfish; believing that one is the center of everything",
    "Egregious": "extremely bad; flagrant",
    # Section 37
    "Elicit": "to bring out; to call forth",
    "Elliptical": "oval; missing a word or words; obscure",
    "Elusive": "hard to pin down; evasive",
    "Emigrate": "to leave a country permanently; to expatriate",
    "Eminent": "well-known and respected; standing out from all others in quality or accomplishment; outstanding",
    "Empirical": "relying on experience or observation; not merely theoretical",
    # Section 38
    "Emulate": "to strive to equal or excel, usually through imitation",
    "Encroach": "to make gradual or stealthy inroads into; to trespass",
    "Endemic": "native; restricted to a particular region or era; indigenous",
    "Enervate": "to reduce the strength or energy of, especially to do so gradually",
    "Enfranchise": "to grant the privileges of citizenship, especially the right to vote",
    "Engender": "to bring into existence; to create; to cause",
    "Enigma": "a mystery",
    "Enormity": "extreme evil; a hideous offense; immensity",
    "Ephemeral": "lasting a very short time",
    # Section 39
    "Epigram": "a brief and usually witty or satirical saying",
    "Epitome": "a brief summary that captures the meaning of the whole; the perfect example"
    " of something; a paradigm",
    "Equanimity": "composure; calm",
    "Equitable": "fair",
    "Equivocal": "ambiguous; intentionally confusing; capable of being interpreted in more than one way",
    "Erudite": "scholarly; deeply learned",
    # Section 40
    "Esoteric": "hard to understand; understood by only a select few; peculiar",
    "Espouse": "to support; to advocate",
    "Ethereal": "heavenly; as light and insubstantial as a gas or ether",
    "Euphemism": "a pleasant or inoffensive expression used in place of an unpleasant or offensive one",
    "Evanescent": "fleeting; vanishing; happening for only the briefest period",
    "Exacerbate": "to make worse",
    "Exacting": "extremely demanding; difficult; requiring great skill or care",
    "Exalt": "to raise high; to glorify",
    "Exasperate": "to annoy thoroughly; to make very angry; to try the patience of",
    "Exemplify": "to illustrate by example; to serve as a good example",
    "Exhaustive": "thorough; rigorous; complete; painstaking",
    "Exhort": "to urge strongly; to give a serious warning to",
    # Section 41
    "Exigency": "an emergency; an urgency",
    "Existential": "having to do with existence; having to do with the body of thought"
    " called existentialism, which basically holds that human beings are responsible"
    " for their own actions but is other too complicated to summarize in a single sentence",
    "Exonerate": "to free completely from blame; to exculpate",
    "Expatriate": "to throw (someone) out of his or her native land; to move away from one's native land; to emigrate",
    "Expedient": "providing an immediate advantage; serving one's immediate self-interest; practical",
    "Expedite": "to speed up or ease the progress of",
    "Explicit": "clearly and directly expressed",
    "Extol": "to praise highly; to laud",
    "Extraneous": "unnecessary; irrelevant; extra",
    "Extrapolate": "to project or deduce from something known; to infer",
    "Extricate": "to free from difficulty",
    "Extrovert": "an open, outgoing person; a person whose attention is focused on"
    " others rather than on himself or herself",
    "Exult": "to rejoice; to celebrate",
    # Section 42
    "Fabrication": "a lie; something made up",
    "Facetious": "humorous; not serious; clumsily humorous",
    "Facile": "fluent; skillful in a superficial way; easy",
    "Faction": "a group, usually a small part of a larger group, united around some"
    " cause; disagreement within an organization",
    "Farcical": "absurd; ludicrous",
    "Fastidious": "meticulous; demanding; finicky",
    "Fatalist": "someone who believes that future events are already determined and"
    " that humans are powerless to change them",
    "Fatuous": "foolish; silly; idiotic",
    "Fauna": "animals",
    "Fecund": "fertile; productive",
    # Section 43
    "Felicity": "happiness; skillfulness, especially at expressing things; adeptness",
    "Fervor": "great warmth or earnestness; ardor; zeal",
    "Fetter": "to restrain; to hamper",
    "Fidelity": "faithfulness; loyalty",
    "Figurative": "based on figures of speech; expressing something in terms usually used for something else; metaphorical",
    "Finesse": "skillful maneuvering; subtlety; craftiness",
    "Flagrant": "glaringly bad; notorious; scandalous",
    "Flaunt": "to show off; to display ostentatiously",
    "Flout": "to disregard something out of disrespect",
    "Foible": "a minor character flaw",
    "Foment": "to stir up; to instigate",
    # Section 44
    "Forbear": "to refrain from; to abstain",
    "Forego": "to do without; to forbear",
    "Forsake": "to abandon; to renounce; to relinquish",
    "Fortuitous": "accidental; occuring by chance",
    "Founder": "to fail; to collapse; to sink",
    "Fraternal": "like brothers",
    "Frenetic": "frantic; frenzied",
    "Frugal": "economical; penny-pinching",
    "Furtive": "secretive; sly",
    "Futile": "useless; hopeless",
    # Section 45
    "Garrulous": "talkative; chatty",
    "Gauche": "unskillful; awkward; maladriot",
    "Genre": "a type or category, especially of art or writing",
    "Genteel": "refined; polite; aristocratic; affecting refinement",
    "Gesticulate": "to make gestures, especially when speaking or in place of speaking",
    "Glut": "surplus; an overabundance",
    "Grandiloquent": "pompous; using a lot of big, fancy words in an attempt to sound impressive",
    "Grandiose": "absurdly exaggerated",
    "Gratuitous": "given freely (said of something bad); unjustified; unprovoked; uncalled for",
    "Gravity": "seriousness",
    "Gregarious": "sociable; enjoying the company of others",
    "Guile": "cunning; duplicity; artfulness",
    # Section 46
    "Hackneyed": "overused; trite; stale",
    "Hapless": "unlucky",
    "Harbinger": "a forerunner; a signal of",
    "Hedonism": "the pursuit of pleasure as a way of life",
    "Hegemony": "leadership, especially of one nation over another",
    "Heresy": "any belief that is strongly opposed to establised beliefs",
    "Hermetic": "impervious to external influence; airtight",
    "Heyday": "golden age; prime",
    "Hiatus": "a break or interruption, often from work",
    "Hierarchy": "an organization based on rank or degree; pecking order",
    "Histrionic": "overly dramatic; theatrical",
    "Homily": "a sermon",
    "Homogeneous": "uniform; made entirely of one thing",
    "Husbandry": "thrifty managment of resources; live-stock farming",
    "Hyperbole": "an exaggeration used as a figure of speech; exaggeration",
    "Hypothetical": "uncertain; unproven",
    # Section 47
    "Iconoclast": "one who attacks popular beliefs or institutions",
    "Ideology": "a system of social or political ideas",
    "Idiosyncrasy": "a peculiarity; an eccentricity",
    "Idyllic": "charming in a rustic way; naturally peaceful",
    "Ignominy": "deep disgrace",
    "Illicit": "illegal; not permitted",
    "Immigrate": "to move permanently to a new country",
    "Imminent": "just about to happen",
    "Immutable": "unchangeable",
    "Impartial": "fair; not favoring one side or the other; unbiased",
    "Impeccable": "flawless; entirely without sin",
    "Imperial": "like an emperor or an empire",
    # Section 48
    "Impervious": "not allowing anything to pass through; impenetrable",
    "Impetuous": "impulsive; extremely impatient",
    "Implement": "to carry out",
    "Impotent": "powerless; helpless; unable to perform",
    "Impugn": "to attack, especially to attack the truth or integrity of something",
    "Inane": "silly; senseless",
    "Inaugurate": "to begin officially; to induct formally into office",
    # Section 49
    "Incandescent": "brilliant; giving off heat or light",
    "Incantation": "a chant; the repetition of statements or phrases in a way reminiscent of a chant",
    "Incense": "to make very angry",
    "Incessant": "unceasing",
    "Incipient": "beginning; emerging",
    "Incisive": "cutting right to the heart of the matter",
    "Incongruous": "not harmonious; not consistent; not appropriate; not fitting in",
    "Incorrigible": "incapable of being reformed",
    "Increment": "an increase; one is a series of increases",
    "Indifferent": "not caring one way or the other; apathetic; mediocre",
    # Section 50
    "Indigenous": "native; originating in that area",
    "Indigent": "poor",
    "Indignant": "angry, especially as a result of something unjust or unworthy; insulted",
    "Indolent": "lazy",
    "Indulgent": "lenient; yielding to desire",
    "Ineffable": "incapable of being expressed or described",
    "Inept": "clumsy; incompetent; gauche",
    "Inert": "inactive; sluggish; not reacting chemically",
    "Inexorable": "relentless; inevitable; unavoidable",
    "Infamous": "shamefully wicked; having an extremely bad reputation; disgraceful",
    "Infatuated": "foolish; foolishly passionate or attracted; made foolish; foolishly in love",
    # Section 51
    "Infer": "to conclude; to deduce",
    "Infinitesimal": "very, very, very small; infinitely small",
    "Ingenuous": "frank; without deception; simple; artless; charmingly naive",
    "Inherent": "part of the essential nature of something; intrinsic",
    "Injunction": "a command or order, especially a court order",
    "Innate": "existing since birth; inborn; inherent",
    "Innocuous": "harmless; banal",
    "Inordinate": "excessive; unreasonable",
    "Insatiable": "hard or impossible to satisfy; greedy; avaricious",
    # Section 52
    "Insidious": "treacherous; sneaky",
    "Insinuate": "to hint; to creep in",
    "Insipid": "dull; bland; banal",
    "Insolent": "arrogant; insulting",
    "Instigate": "to provoke; to stir up",
    "Insular": "like an island; isolated",
    "Insurgent": "a rebel; someone who revolts against a government",
    "Integral": "essential",
    "Integrate": "to combine two or more things into a whole",
    "Intractable": "uncontrollable; stubborn; disobedient",
    "Intransigent": "uncompromising; stubborn",
    # Section 53
    "Intrinsic": "part of the essential nature of something; inherent",
    "Introspective": "tending to think about oneself; examining one's feelings",
    "Inundate": "to flood; to cover completely with water; to overwhelm",
    "Invective": "insulting or abusive speech",
    "Inveterate": "habitual; firm in habit; deeply rooted",
    "Irascible": "easily angered or provoked; irritable",
    "Ironic": "meaning the opposite of what you seem to say; using words to "
    "mean something other than what they seem to mean",
    "Irrevocable": "irreversible",
    "Itinerant": "moving from place to place",
    # Section 54
    "Judicious": "exercising sound judgement",
    "Juxtapose": "to place side by side",
    "Kinetic": "having to do with motion; lively; active",
    "Labyrinth": "a maze; something like a maze",
    "Laconic": "using few words, especially to the point of seeming rude",
    "Lament": "to mourn",
    "Lampoon": "to satirize; to mock; to parody",
    "Languish": "to become weak, listless, or depressed",
    "Largess": "generous giving of gifts (or the gifts themselves); generosity; philanthropy",
    "Latent": "present but not visible or apparent; potential",
    "Laud": "to praise; to applaud; to extol; to celebrate",
    "Legacy": "something handed down from the past; a bequest",
    "Lethargy": "sluggishness; laziness; drowsiness; indifference",
    "Levity": "lightness; frivolity; unseriousness",
    # Section 55
    "Libel": "a written or published falsehood that injures the reputation of, or defames, someone",
    "Litigate": "to try in court; to engage in legal proceedings",
    "Loquacious": "talking a lot or too much",
    "Lucid": "clear; easy to understand",
    "Lugubrious": "exaggeratedly mournful",
    "Luminous": "giving off light; glowing; bright",
    # Section 56
    "Machination": "scheming activity for an evil purpose",
    "Magnanimous": "forgiving; unresentful; noble in spirit; generous",
    "Magnate": "a rich, powerful, or very successful business-person",
    "Malaise": "a feeling of depression, uneasiness, or queasiness",
    "Malfeasance": "an illegal act, especially by a public official",
    "Malignant": "causing harm",
    "Malinger": "to pretend to be sick to avoid doing work",
    "Malleable": "easy to shape or bend",
    "Mandate": "a command or authorization to do something; the will of the voters "
    "as expressed by the results of an election",
    "Manifest": "visible; evident",
    "Manifesto": "a public declaration of beliefs or principles; usually political ones",
    "Marshal": "to arrange in order; to gather together for the purpose of doing something",
    "Martial": "warlike; having to do with combat",
    "Martyr": "someone who gives up his or her life in pursuit of a cause, "
    "especially a religious one; one who suffers for a cause; one who makes a show "
    "of suffering in order to arouse sympathy",
    "Matriculate": "to enroll, especially at a college",
    # Section 57
    "Maudlin": "silly and overly sentimental",
    "Maverick": "a nonconformist; a rebel",
    "Maxim": "a fundamental principle; an old saying",
    "Mediate": "to help settle differences",
    "Mellifluous": "sweetly flowing",
    "Mendacious": "lying; dishonest",
    "Mendicant": "a beggar",
    "Mentor": "a teacher, tutor, counselor, or coach; especially in buisness;"
    " an experienced person who shows an inexperienced person the ropes",
    "Mercenary": "a hired soldier; someone who will do anything for money",
    "Mercurial": "emotionally unpredictable; rapidly changing in mood",
    "Metamorphosis": "a magical change in form; a striking or sudden change",
    # Section 58
    "Microcosm": "the world in miniature",
    "Milieu": "environmental; surroundings",
    "Minuscule": "very tiny",
    "Misanthropic": "hating mankind",
    "Mitigate": "to moderate the effect of something",
    "Mollify": "to soften; to soothe; to pacify",
    "Monolithic": "massive, solid, uniform, and unyielding",
    "Moribund": "dying",
    "Morose": "gloomy; sullen",
    "Mortify": "to humilitate",
    "Mundane": "ordinary; pretty boring; not heavenly and eternal",
    "Munificent": "very generous; lavish",
    "Myopia": "nearsightedness; lack of foresight",
    "Myriad": "a huge number",
    # Section 59
    "Narcissism": "excessive love of one's body or oneself",
    "Nebulous": "vague; hazy; indistinct",
    "Nefarious": "evil; flagrantly wicked",
    "Neologism": "a new word or phrase; a new usage of a word",
    "Nepotism": "showing favoritism to friends or family in business or politics",
    "Nihilism": "the belief that there are no values or morals in the universe",
    "Nominal": "in name only; insignificant; A-OK (during rocket launches)",
    "Nostalgia": "sentimental longing for the past; homesickness",
    "Notorious": "famous for something bad",
    "Novel": "new; original",
    "Noxious": "harmful; offensive",
    "Nuance": "a subtle difference or distinction",
    # Section 60
    "Obdurate": "stubborn and insensitive",
    "Obfuscate": "to darken; to confuse; to make confusing",
    "Oblique": "indirect; at an angle",
    "Oblivion": "total forgetfulness; the state of being forgotten",
    "Obscure": "unknown; hard to understand; dark",
    "Obsequious": "fawning; subservient; sucking up to",
    "Obtuse": "insensitive; blockheaded",
    "Officious": "annoyingly eager to help or advise",
    "Onerous": "burdensome; oppressive",
    "Opaque": "impossible to see through; impossible to understand",
    "Opulent": "luxurious",
    "Orthodox": "conventional; adhering to established principles or doctrines, "
    "especially in religion; by the book",
    "Ostensible": "apparent (but misleading); professed",
    "Ostentatious": "excessively conspicuous; showing off",
    # Section 61
    "Pacify": "to calm someone down; to placate",
    "Painstaking": "extremely careful; taking pains",
    "Palliate": "to relieve or alleviate something without getting rid of the problem; "
    "to assuage; to mitigate",
    "Palpable": "capable of being touched; obvious; tangible",
    "Paltry": "insignificant; worthless",
    "Panacea": "something that cures everything",
    "Paradigm": "a model or example",
    "Paradox": "a true statement or phenomenon that nonetheless seems to contradict itself; "
    "an untrue statement or phenomenon that nonetheless seems logical",
    "Parochial": "narrow or confined in point of view; provincial",
    "Parody": "a satirical imitation",
    "Parsimonious": "stingy",
    "Partisan": "one who supports a particular person, cause, or idea",
    # Section 62
    "Patent": "obvious",
    "Paternal": "fatherly; fatherlike",
    "Pathology": "the science of diseases",
    "Patriarch": "the male head of a family or tribe",
    "Patrician": "a person of noble birth; an aristocrat",
    "Patronize": "to treat as an inferior; to condescend to",
    "Paucity": "scarcity",
    "Peccadillo": "a minor offense",
    "Pedantic": "boringly scholarly or academic", 
    "Pedestrian": "unimaginative; banal",
    "Pejorative": "negative; disparaging",
    "Penchant": "a strong taste or liking for something; a predilection",
    "Penitent": "sorry; repentant; contrite", 
    "Pensive": "thoughtful and sad",
    # Section 63
}

print(f"Current number of words = {len(word_dict)}")
